# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 167)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 23, 341, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dbTypeLabel = QtWidgets.QLabel(self.widget)
        self.dbTypeLabel.setObjectName("dbTypeLabel")
        self.gridLayout.addWidget(self.dbTypeLabel, 0, 0, 1, 1)
        self.dbTypeComboBox = QtWidgets.QComboBox(self.widget)
        self.dbTypeComboBox.setObjectName("dbTypeComboBox")
        self.dbTypeComboBox.addItem("")
        self.dbTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.dbTypeComboBox, 0, 1, 1, 1)
        self.dbLabel = QtWidgets.QLabel(self.widget)
        self.dbLabel.setObjectName("dbLabel")
        self.gridLayout.addWidget(self.dbLabel, 1, 0, 1, 1)
        self.dblineEdit = QtWidgets.QLineEdit(self.widget)
        self.dblineEdit.setObjectName("dblineEdit")
        self.gridLayout.addWidget(self.dblineEdit, 1, 1, 1, 1)
        self.usernameLabel = QtWidgets.QLabel(self.widget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 2, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout.addWidget(self.usernameLineEdit, 2, 1, 1, 1)
        self.pwdLable = QtWidgets.QLabel(self.widget)
        self.pwdLable.setObjectName("pwdLable")
        self.gridLayout.addWidget(self.pwdLable, 3, 0, 1, 1)
        self.pwdLineEdit = QtWidgets.QLineEdit(self.widget)
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.gridLayout.addWidget(self.pwdLineEdit, 3, 1, 1, 1)
        self.dbTypeLabel.setBuddy(self.dbTypeComboBox)
        self.dbLabel.setBuddy(self.dblineEdit)
        self.usernameLabel.setBuddy(self.usernameLineEdit)
        self.pwdLable.setBuddy(self.pwdLineEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dbTypeLabel.setText(_translate("Dialog", "dbType:"))
        self.dbTypeComboBox.setItemText(0, _translate("Dialog", "Local"))
        self.dbTypeComboBox.setItemText(1, _translate("Dialog", "Server"))
        self.dbLabel.setText(_translate("Dialog", "database:"))
        self.dblineEdit.setText(_translate("Dialog", "testdb"))
        self.usernameLabel.setText(_translate("Dialog", "User Name:"))
        self.usernameLineEdit.setText(_translate("Dialog", "root"))
        self.pwdLable.setText(_translate("Dialog", "password:"))
        self.pwdLineEdit.setText(_translate("Dialog", "yp*963."))
